#https://docs.docker.com/compose/compose-file/compose-file-v3/
version: '3'
services:

  oracle_service:   
    container_name: oracle 
    image: jaspeen/oracle-xe-11g  
    volumes:
      - /home/ubuntu/oracle:/u01/app/oracle 
    ports:
      - 1521:1521  
    networks: 
      - test2
       
  web_service:
    container_name: web
    image: parkhj0209/hyungjuns.com
    ports:
      - '80:80'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://43.203.174.44:3306/hj
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: [password]
      restart: always
    networks: 
      - test2
    depends_on:
     - oracle_service
   
networks: 
  test2: