#https://docs.docker.com/compose/compose-file/compose-file-v3/
version: '3'
services:

  oracle_service:   
    container_name: oracle 
    image: jaspeen/oracle-xe-11g  
    volumes:
      - /home/ubuntu/oracle:/u01/app/oracle 
    ports:
      - 1521:1521  
    networks: 
      - test2
       
  web_service:
    container_name: web
    image: parkhj0209/hyungjuns.com
    ports:
      - '9400:9400'
    environment:
      spring.datasource.url: jdbc:oracle:thin:@oracle:1521:xe
      spring.datasource.hikari.data-source-properties.oracle.jdbc.timezoneAsRegion: "Asia/Seoul"
      spring.datasource.password: hj
    networks: 
      - test2
    depends_on:
     - oracle_service
   
networks: 
  test2: